AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String

Resources: 
  SSL:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub www.${DomainName}
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS